from . import barcode_rule
from . import ir_actions_report
from . import product_removal
from . import stock_putaway_rule
from . import res_company
from . import res_partner
from . import res_users
from . import res_config_settings
from . import stock_location
from . import stock_route
from . import stock_move
from . import stock_move_line
from . import stock_orderpoint
from . import stock_lot
from . import stock_picking_type
from . import stock_picking
from . import stock_quant
from . import stock_quant_package
from . import stock_replenish_mixin
from . import stock_rule
from . import stock_warehouse
from . import stock_scrap
from . import uom_uom
from . import product_category
from . import product_product
from . import product_template
from . import stock_package_level
from . import stock_package_type
from . import stock_storage_category
