{
    "name": "Purchase",
    "version": "1.2",
    "category": "Inventory/Purchase",
    "sequence": 35,
    "summary": "Purchase orders, tenders and agreements",
    "website": "https://www.odoo.com/app/purchase",
    "depends": ["account"],
    "data": [
        "security/ir_module_category.xml",
        "security/res_groups.xml",
        "security/ir_rule.xml",
        "security/ir.model.access.csv",
        "data/digest_data.xml",
        "data/purchase_data.xml",
        "data/ir_cron_data.xml",
        "data/purchase_reports.xml",
        "data/mail_template_data.xml",
        "data/mail_templates.xml",
        "data/approval_category_data.xml",
        "data/purchase_tour.xml",
        "views/account_move_views.xml",
        "views/portal_templates.xml",
        "views/product_template_views.xml",
        "views/product_product_views.xml",
        "views/product_supplierinfo_views.xml",
        "views/purchase_order_views.xml",
        "views/purchase_order_line_views.xml",
        "views/res_partner_views.xml",
        "report/purchase_report_views.xml",
        "report/purchase_order_templates.xml",
        "report/purchase_quotation_templates.xml",
        "wizard/res_config_settings_views.xml",
        "wizard/bill_to_po_wizard_views.xml",
        "wizard/purchase_bill_union_views.xml",
        "wizard/purchase_bill_line_match_views.xml",
        "views/purchase_menu.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "purchase/static/src/components/**/*",
            "purchase/static/src/product_catalog/**/*",
            "purchase/static/src/toaster_button/*",
            "purchase/static/src/views/*.js",
            "purchase/static/src/js/tours/purchase.js",
            "purchase/static/src/js/tours/purchase_steps.js",
            "purchase/static/src/**/*.xml",
            "purchase/static/src/**/*.scss",
        ],
        "web.assets_frontend": [
            "purchase/static/src/interactions/**/*",
        ],
    },
    "demo": [
        "data/purchase_demo.xml",
    ],
    "installable": True,
    "application": True,
    "license": "LGPL-3",
}
