from . import account_move
from . import account_move_line
from . import product_template
from . import res_company
from . import res_users
from . import sale_order
from . import sale_order_line
from . import stock_picking
from . import stock_route
from . import stock_move
from . import stock_move_line
from . import procurement_group
from . import stock_rule
from . import stock_lot
