from . import account_analytic_applicability
from . import account_move
from . import account_move_line
from . import account_tax
from . import ir_actions_report
from . import product_template
from . import product_product
from . import product_supplierinfo
from . import res_company
from . import res_partner
from . import purchase_order
from . import purchase_order_line
