from . import account_analytic_applicability
from . import account_move
from . import account_move_line
from . import chart_template
from . import crm_team
from . import ir_config_parameter
from . import payment_provider
from . import payment_transaction
from . import product_attribute_custom_value
from . import product_category
from . import product_document
from . import product_product
from . import product_template
from . import res_company
from . import res_partner
from . import utm_campaign
from . import sale_order
from . import sale_order_line
